spring.jpa:
  properties:
    hibernate:
      search:
        default:
          directory_provider: filesystem
          indexBase: /home/imarket/tmp/indexed
#security:
#  enabled: true
#  ignore:
#    uri: /thereisnouri
#jwt:
#  secret: imarket@!123#$';
#  access_token_validity: 60
#  refresh_token_validity: 420
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: imarket
    url: jdbc:mysql://localhost:3306/imarket?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: imarket
    hikari:
      max-lifetime: 18000000
      leak-detection-threshold: 3000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
spring.redis:
  enable: true
  lettuce.pool:
    max-active: 10
    max-idle: 10
    min-idle: 2
  port: 6379
  host: 127.0.0.1

